/** Single import surface for Phosphor icons used across the app. */
export {
  ArrowsDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  Bell,
  Buildings,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUpDown,
  ChartLineUp,
  ChatCircleDots,
  Check,
  CheckCircle,
  ClockCounterClockwise,
  Columns,
  Cube,
  CurrencyInr,
  DotsThree,
  Envelope,
  FileText,
  Funnel,
  Gauge,
  Gear,
  Info,
  List,
  ListChecks,
  MagnifyingGlass,
  Package,
  PaperPlaneTilt,
  Pencil,
  Plus,
  Prohibit,
  Receipt,
  Repeat,
  ShieldCheck,
  SignOut,
  SlidersHorizontal,
  Sparkle,
  Stack,
  Storefront,
  Tag,
  Trash,
  TrendUp,
  Truck,
  User as UserIcon,
  Users,
  Warehouse,
  Warning,
  WarningCircle,
  X,
  XCircle,
} from "@phosphor-icons/react/dist/ssr";

export { PauseIcon as Pause, PlayIcon as Play } from "@phosphor-icons/react/dist/ssr";
